intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libA%lib{A}

lib{B}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBB_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBB_SHARED_BUILD

# Export options.
#
lib{B}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{B}: cxx.export.poptions += -DLIBB_STATIC
libs{B}: cxx.export.poptions += -DLIBB_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{B}: bin.lib.version = "-$version.project_id"
else
  lib{B}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libB/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libB/
  install.subdirs = true
}
